### ISSUE TITLE
undefined method "followers" for nilClass

### ISSUE THREAD

**Issue by jamiew** [clearbit/clearbit-leadscore#5]
I assume this gem is deprecated? 

`clearbit` from clearbit-ruby works fine, but this tool throws an error on every email address I put in. Just thought I'd share in case you didn't know

```
/Users/jamie/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/clearbit-leadscore-0.0.5/lib/clearbit/lead_score/score.rb:35:in `calculate': undefined method `followers' for nil:NilClass (NoMethodError)
        from /Users/jamie/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/clearbit-leadscore-0.0.5/lib/clearbit/lead_score.rb:51:in `lookup'
        from /Users/jamie/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/clearbit-leadscore-0.0.5/bin/clearbit-leadscore:45:in `<top (required)>'
        from /Users/jamie/.rbenv/versions/2.2.2/bin/clearbit-leadscore:23:in `load'
        from /Users/jamie/.rbenv/versions/2.2.2/bin/clearbit-leadscore:23:in `<main>'
```

**Comment by CharleyMa** [comment]
Also getting this error! :)
